/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as NewRouteImport } from './routes/new'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as AppRouteImport } from './routes/_app'
import { Route as OnboardRouteRouteImport } from './routes/onboard/route'
import { Route as SearchIndexRouteImport } from './routes/search/index'
import { Route as OnboardIndexRouteImport } from './routes/onboard/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as TSlugRouteImport } from './routes/t.$slug'
import { Route as SettingsBaseRouteImport } from './routes/settings/_base'
import { Route as AppExploreRouteImport } from './routes/_app.explore'
import { Route as AppBookmarksRouteImport } from './routes/_app.bookmarks'
import { Route as UAtChar123usernameChar125IndexRouteImport } from './routes/u/@{$username}/index'
import { Route as SettingsBaseIndexRouteImport } from './routes/settings/_base.index'
import { Route as UAtChar123usernameChar125SlugRouteImport } from './routes/u/@{$username}/$slug'
import { Route as SettingsBaseEmailRouteImport } from './routes/settings/_base.email'
import { Route as SettingsBaseAccountRouteImport } from './routes/settings/_base.account'
import { Route as DashboardPublicationIdPubRouteImport } from './routes/dashboard/$publicationId/_pub'
import { Route as ApiTrpcSplatRouteImport } from './routes/api.trpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DashboardPublicationIdPubIndexRouteImport } from './routes/dashboard/$publicationId/_pub.index'
import { Route as OnboardBlogSetupChar123RedirectChar125RouteImport } from './routes/onboard/blog.setup.{-$redirect}'
import { Route as DashboardPublicationIdPubSeriesRouteImport } from './routes/dashboard/$publicationId/_pub.series'
import { Route as DashboardPublicationIdPubPostsRouteImport } from './routes/dashboard/$publicationId/_pub.posts'
import { Route as DashboardPublicationIdPubGeneralRouteImport } from './routes/dashboard/$publicationId/_pub.general'
import { Route as DashboardPublicationIdPubAppearanceRouteImport } from './routes/dashboard/$publicationId/_pub.appearance'

const SettingsRouteImport = createFileRoute('/settings')()
const DashboardPublicationIdRouteImport = createFileRoute(
  '/dashboard/$publicationId',
)()

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardRouteRoute = OnboardRouteRouteImport.update({
  id: '/onboard',
  path: '/onboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPublicationIdRoute = DashboardPublicationIdRouteImport.update({
  id: '/dashboard/$publicationId',
  path: '/dashboard/$publicationId',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchIndexRoute = SearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardIndexRoute = OnboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardRouteRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const TSlugRoute = TSlugRouteImport.update({
  id: '/t/$slug',
  path: '/t/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsBaseRoute = SettingsBaseRouteImport.update({
  id: '/_base',
  getParentRoute: () => SettingsRoute,
} as any)
const AppExploreRoute = AppExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AppRoute,
} as any)
const AppBookmarksRoute = AppBookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => AppRoute,
} as any)
const UAtChar123usernameChar125IndexRoute =
  UAtChar123usernameChar125IndexRouteImport.update({
    id: '/u/@{$username}/',
    path: '/u/@{$username}/',
    getParentRoute: () => rootRouteImport,
  } as any)
const SettingsBaseIndexRoute = SettingsBaseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsBaseRoute,
} as any)
const UAtChar123usernameChar125SlugRoute =
  UAtChar123usernameChar125SlugRouteImport.update({
    id: '/u/@{$username}/$slug',
    path: '/u/@{$username}/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)
const SettingsBaseEmailRoute = SettingsBaseEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => SettingsBaseRoute,
} as any)
const SettingsBaseAccountRoute = SettingsBaseAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => SettingsBaseRoute,
} as any)
const DashboardPublicationIdPubRoute =
  DashboardPublicationIdPubRouteImport.update({
    id: '/_pub',
    getParentRoute: () => DashboardPublicationIdRoute,
  } as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPublicationIdPubIndexRoute =
  DashboardPublicationIdPubIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardPublicationIdPubRoute,
  } as any)
const OnboardBlogSetupChar123RedirectChar125Route =
  OnboardBlogSetupChar123RedirectChar125RouteImport.update({
    id: '/blog/setup/{-$redirect}',
    path: '/blog/setup/{-$redirect}',
    getParentRoute: () => OnboardRouteRoute,
  } as any)
const DashboardPublicationIdPubSeriesRoute =
  DashboardPublicationIdPubSeriesRouteImport.update({
    id: '/series',
    path: '/series',
    getParentRoute: () => DashboardPublicationIdPubRoute,
  } as any)
const DashboardPublicationIdPubPostsRoute =
  DashboardPublicationIdPubPostsRouteImport.update({
    id: '/posts',
    path: '/posts',
    getParentRoute: () => DashboardPublicationIdPubRoute,
  } as any)
const DashboardPublicationIdPubGeneralRoute =
  DashboardPublicationIdPubGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => DashboardPublicationIdPubRoute,
  } as any)
const DashboardPublicationIdPubAppearanceRoute =
  DashboardPublicationIdPubAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => DashboardPublicationIdPubRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/onboard': typeof OnboardRouteRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/new': typeof NewRoute
  '/notifications': typeof NotificationsRoute
  '/pricing': typeof PricingRoute
  '/bookmarks': typeof AppBookmarksRoute
  '/explore': typeof AppExploreRoute
  '/settings': typeof SettingsBaseRouteWithChildren
  '/t/$slug': typeof TSlugRoute
  '/': typeof AppIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/onboard/': typeof OnboardIndexRoute
  '/search': typeof SearchIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/dashboard/$publicationId': typeof DashboardPublicationIdPubRouteWithChildren
  '/settings/account': typeof SettingsBaseAccountRoute
  '/settings/email': typeof SettingsBaseEmailRoute
  '/u/@{$username}/$slug': typeof UAtChar123usernameChar125SlugRoute
  '/settings/': typeof SettingsBaseIndexRoute
  '/u/@{$username}': typeof UAtChar123usernameChar125IndexRoute
  '/dashboard/$publicationId/appearance': typeof DashboardPublicationIdPubAppearanceRoute
  '/dashboard/$publicationId/general': typeof DashboardPublicationIdPubGeneralRoute
  '/dashboard/$publicationId/posts': typeof DashboardPublicationIdPubPostsRoute
  '/dashboard/$publicationId/series': typeof DashboardPublicationIdPubSeriesRoute
  '/onboard/blog/setup/{-$redirect}': typeof OnboardBlogSetupChar123RedirectChar125Route
  '/dashboard/$publicationId/': typeof DashboardPublicationIdPubIndexRoute
}
export interface FileRoutesByTo {
  '/changelog': typeof ChangelogRoute
  '/new': typeof NewRoute
  '/notifications': typeof NotificationsRoute
  '/pricing': typeof PricingRoute
  '/bookmarks': typeof AppBookmarksRoute
  '/explore': typeof AppExploreRoute
  '/settings': typeof SettingsBaseIndexRoute
  '/t/$slug': typeof TSlugRoute
  '/': typeof AppIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/onboard': typeof OnboardIndexRoute
  '/search': typeof SearchIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/dashboard/$publicationId': typeof DashboardPublicationIdPubIndexRoute
  '/settings/account': typeof SettingsBaseAccountRoute
  '/settings/email': typeof SettingsBaseEmailRoute
  '/u/@{$username}/$slug': typeof UAtChar123usernameChar125SlugRoute
  '/u/@{$username}': typeof UAtChar123usernameChar125IndexRoute
  '/dashboard/$publicationId/appearance': typeof DashboardPublicationIdPubAppearanceRoute
  '/dashboard/$publicationId/general': typeof DashboardPublicationIdPubGeneralRoute
  '/dashboard/$publicationId/posts': typeof DashboardPublicationIdPubPostsRoute
  '/dashboard/$publicationId/series': typeof DashboardPublicationIdPubSeriesRoute
  '/onboard/blog/setup/{-$redirect}': typeof OnboardBlogSetupChar123RedirectChar125Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/onboard': typeof OnboardRouteRouteWithChildren
  '/_app': typeof AppRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/new': typeof NewRoute
  '/notifications': typeof NotificationsRoute
  '/pricing': typeof PricingRoute
  '/_app/bookmarks': typeof AppBookmarksRoute
  '/_app/explore': typeof AppExploreRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/_base': typeof SettingsBaseRouteWithChildren
  '/t/$slug': typeof TSlugRoute
  '/_app/': typeof AppIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/onboard/': typeof OnboardIndexRoute
  '/search/': typeof SearchIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/dashboard/$publicationId': typeof DashboardPublicationIdRouteWithChildren
  '/dashboard/$publicationId/_pub': typeof DashboardPublicationIdPubRouteWithChildren
  '/settings/_base/account': typeof SettingsBaseAccountRoute
  '/settings/_base/email': typeof SettingsBaseEmailRoute
  '/u/@{$username}/$slug': typeof UAtChar123usernameChar125SlugRoute
  '/settings/_base/': typeof SettingsBaseIndexRoute
  '/u/@{$username}/': typeof UAtChar123usernameChar125IndexRoute
  '/dashboard/$publicationId/_pub/appearance': typeof DashboardPublicationIdPubAppearanceRoute
  '/dashboard/$publicationId/_pub/general': typeof DashboardPublicationIdPubGeneralRoute
  '/dashboard/$publicationId/_pub/posts': typeof DashboardPublicationIdPubPostsRoute
  '/dashboard/$publicationId/_pub/series': typeof DashboardPublicationIdPubSeriesRoute
  '/onboard/blog/setup/{-$redirect}': typeof OnboardBlogSetupChar123RedirectChar125Route
  '/dashboard/$publicationId/_pub/': typeof DashboardPublicationIdPubIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/onboard'
    | '/changelog'
    | '/new'
    | '/notifications'
    | '/pricing'
    | '/bookmarks'
    | '/explore'
    | '/settings'
    | '/t/$slug'
    | '/'
    | '/dashboard'
    | '/onboard/'
    | '/search'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/dashboard/$publicationId'
    | '/settings/account'
    | '/settings/email'
    | '/u/@{$username}/$slug'
    | '/settings/'
    | '/u/@{$username}'
    | '/dashboard/$publicationId/appearance'
    | '/dashboard/$publicationId/general'
    | '/dashboard/$publicationId/posts'
    | '/dashboard/$publicationId/series'
    | '/onboard/blog/setup/{-$redirect}'
    | '/dashboard/$publicationId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/changelog'
    | '/new'
    | '/notifications'
    | '/pricing'
    | '/bookmarks'
    | '/explore'
    | '/settings'
    | '/t/$slug'
    | '/'
    | '/dashboard'
    | '/onboard'
    | '/search'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/dashboard/$publicationId'
    | '/settings/account'
    | '/settings/email'
    | '/u/@{$username}/$slug'
    | '/u/@{$username}'
    | '/dashboard/$publicationId/appearance'
    | '/dashboard/$publicationId/general'
    | '/dashboard/$publicationId/posts'
    | '/dashboard/$publicationId/series'
    | '/onboard/blog/setup/{-$redirect}'
  id:
    | '__root__'
    | '/onboard'
    | '/_app'
    | '/changelog'
    | '/new'
    | '/notifications'
    | '/pricing'
    | '/_app/bookmarks'
    | '/_app/explore'
    | '/settings'
    | '/settings/_base'
    | '/t/$slug'
    | '/_app/'
    | '/dashboard/'
    | '/onboard/'
    | '/search/'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/dashboard/$publicationId'
    | '/dashboard/$publicationId/_pub'
    | '/settings/_base/account'
    | '/settings/_base/email'
    | '/u/@{$username}/$slug'
    | '/settings/_base/'
    | '/u/@{$username}/'
    | '/dashboard/$publicationId/_pub/appearance'
    | '/dashboard/$publicationId/_pub/general'
    | '/dashboard/$publicationId/_pub/posts'
    | '/dashboard/$publicationId/_pub/series'
    | '/onboard/blog/setup/{-$redirect}'
    | '/dashboard/$publicationId/_pub/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  OnboardRouteRoute: typeof OnboardRouteRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  ChangelogRoute: typeof ChangelogRoute
  NewRoute: typeof NewRoute
  NotificationsRoute: typeof NotificationsRoute
  PricingRoute: typeof PricingRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  TSlugRoute: typeof TSlugRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  SearchIndexRoute: typeof SearchIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
  DashboardPublicationIdRoute: typeof DashboardPublicationIdRouteWithChildren
  UAtChar123usernameChar125SlugRoute: typeof UAtChar123usernameChar125SlugRoute
  UAtChar123usernameChar125IndexRoute: typeof UAtChar123usernameChar125IndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboard': {
      id: '/onboard'
      path: '/onboard'
      fullPath: '/onboard'
      preLoaderRoute: typeof OnboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$publicationId': {
      id: '/dashboard/$publicationId'
      path: '/dashboard/$publicationId'
      fullPath: '/dashboard/$publicationId'
      preLoaderRoute: typeof DashboardPublicationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/': {
      id: '/search/'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboard/': {
      id: '/onboard/'
      path: '/'
      fullPath: '/onboard/'
      preLoaderRoute: typeof OnboardIndexRouteImport
      parentRoute: typeof OnboardRouteRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/t/$slug': {
      id: '/t/$slug'
      path: '/t/$slug'
      fullPath: '/t/$slug'
      preLoaderRoute: typeof TSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/_base': {
      id: '/settings/_base'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsBaseRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/_app/explore': {
      id: '/_app/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof AppExploreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bookmarks': {
      id: '/_app/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof AppBookmarksRouteImport
      parentRoute: typeof AppRoute
    }
    '/u/@{$username}/': {
      id: '/u/@{$username}/'
      path: '/u/@{$username}'
      fullPath: '/u/@{$username}'
      preLoaderRoute: typeof UAtChar123usernameChar125IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/_base/': {
      id: '/settings/_base/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsBaseIndexRouteImport
      parentRoute: typeof SettingsBaseRoute
    }
    '/u/@{$username}/$slug': {
      id: '/u/@{$username}/$slug'
      path: '/u/@{$username}/$slug'
      fullPath: '/u/@{$username}/$slug'
      preLoaderRoute: typeof UAtChar123usernameChar125SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/_base/email': {
      id: '/settings/_base/email'
      path: '/email'
      fullPath: '/settings/email'
      preLoaderRoute: typeof SettingsBaseEmailRouteImport
      parentRoute: typeof SettingsBaseRoute
    }
    '/settings/_base/account': {
      id: '/settings/_base/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof SettingsBaseAccountRouteImport
      parentRoute: typeof SettingsBaseRoute
    }
    '/dashboard/$publicationId/_pub': {
      id: '/dashboard/$publicationId/_pub'
      path: '/dashboard/$publicationId'
      fullPath: '/dashboard/$publicationId'
      preLoaderRoute: typeof DashboardPublicationIdPubRouteImport
      parentRoute: typeof DashboardPublicationIdRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$publicationId/_pub/': {
      id: '/dashboard/$publicationId/_pub/'
      path: '/'
      fullPath: '/dashboard/$publicationId/'
      preLoaderRoute: typeof DashboardPublicationIdPubIndexRouteImport
      parentRoute: typeof DashboardPublicationIdPubRoute
    }
    '/onboard/blog/setup/{-$redirect}': {
      id: '/onboard/blog/setup/{-$redirect}'
      path: '/blog/setup/{-$redirect}'
      fullPath: '/onboard/blog/setup/{-$redirect}'
      preLoaderRoute: typeof OnboardBlogSetupChar123RedirectChar125RouteImport
      parentRoute: typeof OnboardRouteRoute
    }
    '/dashboard/$publicationId/_pub/series': {
      id: '/dashboard/$publicationId/_pub/series'
      path: '/series'
      fullPath: '/dashboard/$publicationId/series'
      preLoaderRoute: typeof DashboardPublicationIdPubSeriesRouteImport
      parentRoute: typeof DashboardPublicationIdPubRoute
    }
    '/dashboard/$publicationId/_pub/posts': {
      id: '/dashboard/$publicationId/_pub/posts'
      path: '/posts'
      fullPath: '/dashboard/$publicationId/posts'
      preLoaderRoute: typeof DashboardPublicationIdPubPostsRouteImport
      parentRoute: typeof DashboardPublicationIdPubRoute
    }
    '/dashboard/$publicationId/_pub/general': {
      id: '/dashboard/$publicationId/_pub/general'
      path: '/general'
      fullPath: '/dashboard/$publicationId/general'
      preLoaderRoute: typeof DashboardPublicationIdPubGeneralRouteImport
      parentRoute: typeof DashboardPublicationIdPubRoute
    }
    '/dashboard/$publicationId/_pub/appearance': {
      id: '/dashboard/$publicationId/_pub/appearance'
      path: '/appearance'
      fullPath: '/dashboard/$publicationId/appearance'
      preLoaderRoute: typeof DashboardPublicationIdPubAppearanceRouteImport
      parentRoute: typeof DashboardPublicationIdPubRoute
    }
  }
}

interface OnboardRouteRouteChildren {
  OnboardIndexRoute: typeof OnboardIndexRoute
  OnboardBlogSetupChar123RedirectChar125Route: typeof OnboardBlogSetupChar123RedirectChar125Route
}

const OnboardRouteRouteChildren: OnboardRouteRouteChildren = {
  OnboardIndexRoute: OnboardIndexRoute,
  OnboardBlogSetupChar123RedirectChar125Route:
    OnboardBlogSetupChar123RedirectChar125Route,
}

const OnboardRouteRouteWithChildren = OnboardRouteRoute._addFileChildren(
  OnboardRouteRouteChildren,
)

interface AppRouteChildren {
  AppBookmarksRoute: typeof AppBookmarksRoute
  AppExploreRoute: typeof AppExploreRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBookmarksRoute: AppBookmarksRoute,
  AppExploreRoute: AppExploreRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface SettingsBaseRouteChildren {
  SettingsBaseAccountRoute: typeof SettingsBaseAccountRoute
  SettingsBaseEmailRoute: typeof SettingsBaseEmailRoute
  SettingsBaseIndexRoute: typeof SettingsBaseIndexRoute
}

const SettingsBaseRouteChildren: SettingsBaseRouteChildren = {
  SettingsBaseAccountRoute: SettingsBaseAccountRoute,
  SettingsBaseEmailRoute: SettingsBaseEmailRoute,
  SettingsBaseIndexRoute: SettingsBaseIndexRoute,
}

const SettingsBaseRouteWithChildren = SettingsBaseRoute._addFileChildren(
  SettingsBaseRouteChildren,
)

interface SettingsRouteChildren {
  SettingsBaseRoute: typeof SettingsBaseRouteWithChildren
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsBaseRoute: SettingsBaseRouteWithChildren,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface DashboardPublicationIdPubRouteChildren {
  DashboardPublicationIdPubAppearanceRoute: typeof DashboardPublicationIdPubAppearanceRoute
  DashboardPublicationIdPubGeneralRoute: typeof DashboardPublicationIdPubGeneralRoute
  DashboardPublicationIdPubPostsRoute: typeof DashboardPublicationIdPubPostsRoute
  DashboardPublicationIdPubSeriesRoute: typeof DashboardPublicationIdPubSeriesRoute
  DashboardPublicationIdPubIndexRoute: typeof DashboardPublicationIdPubIndexRoute
}

const DashboardPublicationIdPubRouteChildren: DashboardPublicationIdPubRouteChildren =
  {
    DashboardPublicationIdPubAppearanceRoute:
      DashboardPublicationIdPubAppearanceRoute,
    DashboardPublicationIdPubGeneralRoute:
      DashboardPublicationIdPubGeneralRoute,
    DashboardPublicationIdPubPostsRoute: DashboardPublicationIdPubPostsRoute,
    DashboardPublicationIdPubSeriesRoute: DashboardPublicationIdPubSeriesRoute,
    DashboardPublicationIdPubIndexRoute: DashboardPublicationIdPubIndexRoute,
  }

const DashboardPublicationIdPubRouteWithChildren =
  DashboardPublicationIdPubRoute._addFileChildren(
    DashboardPublicationIdPubRouteChildren,
  )

interface DashboardPublicationIdRouteChildren {
  DashboardPublicationIdPubRoute: typeof DashboardPublicationIdPubRouteWithChildren
}

const DashboardPublicationIdRouteChildren: DashboardPublicationIdRouteChildren =
  {
    DashboardPublicationIdPubRoute: DashboardPublicationIdPubRouteWithChildren,
  }

const DashboardPublicationIdRouteWithChildren =
  DashboardPublicationIdRoute._addFileChildren(
    DashboardPublicationIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  OnboardRouteRoute: OnboardRouteRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  ChangelogRoute: ChangelogRoute,
  NewRoute: NewRoute,
  NotificationsRoute: NotificationsRoute,
  PricingRoute: PricingRoute,
  SettingsRoute: SettingsRouteWithChildren,
  TSlugRoute: TSlugRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  SearchIndexRoute: SearchIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
  DashboardPublicationIdRoute: DashboardPublicationIdRouteWithChildren,
  UAtChar123usernameChar125SlugRoute: UAtChar123usernameChar125SlugRoute,
  UAtChar123usernameChar125IndexRoute: UAtChar123usernameChar125IndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
